#!/bin/sh
#
# Generate webpage for CoCo
# 
# The schedule can be generated by "scheduleparser.cc"
# 
# The output is intended to be stored in the file "index.html" in the directory ~/git/WebsiteGitHub/teaching/CoCo<YY>/ .
#

PAGEFIRSTHALF="coco26-first-half-of-page.html"
PAGESCHEDULE="coco26-schedule.html"
PAGESECONDHALF="coco26-second-half-of-page.html"
PAGEFOOTER="coco26-footer.html"

OUTPUTFILE="../index.html"


echo "CREATING BACKUP BY DOING cp "$OUTPUTFILE" "$OUTPUTFILE".BAK"
cp $OUTPUTFILE $OUTPUTFILE.BAK

echo "DOING cat "$PAGEFIRSTHALF $PAGESCHEDULE $PAGESECONDHALF" > "$OUTPUTFILE
cat $PAGEFIRSTHALF $PAGESCHEDULE $PAGESECONDHALF > $OUTPUTFILE

echo "ADDING DATE BY DOING date +'Updated %Y-%m-%d' >> "$OUTPUTFILE
date +'Updated %Y-%m-%d' >> $OUTPUTFILE

echo "DOING cat "$PAGEFOOTER" >> "$OUTPUTFILE
cat $PAGEFOOTER >> $OUTPUTFILE

