#!/bin/sh
#
# Generate webpage for proof complexity course 2025/26
# 
# The schedule HTML file is expected to be generated by "scheduleparser.cc"
# 
# The output is intended to be stored in the file "index.html" in the
# directory ~/git/WebsiteGitHub/teaching/proofcplx25/ .
#

PAGEFIRSTHALF="proofcplx25-first-half-of-page.html"
PAGESCHEDULE="proofcplx25-schedule.html"
PAGESECONDHALF="proofcplx25-second-half-of-page.html"
PAGEFOOTER="proofcplx25-footer.html"

OUTPUTFILE="../index.html"

echo "CREATING BACKUP BY DOING cp "$OUTPUTFILE" "$OUTPUTFILE".BAK"
cp $OUTPUTFILE $OUTPUTFILE.BAK

echo "DOING cat "$PAGEFIRSTHALF $PAGESCHEDULE $PAGESECONDHALF" > "$OUTPUTFILE
cat $PAGEFIRSTHALF $PAGESCHEDULE $PAGESECONDHALF > $OUTPUTFILE

echo "ADDING DATE BY DOING date +'Updated %Y-%m-%d' >> "$OUTPUTFILE
date +'Updated %Y-%m-%d' >> $OUTPUTFILE

echo "DOING cat "$PAGEFOOTER" >> "$OUTPUTFILE
cat $PAGEFOOTER >> $OUTPUTFILE

